kind: Template
apiVersion: v1
metadata:
  annotations:
    description: baza pv create template
  name: baza-pv
objects:
- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: gogs-postgres-data-pv
  spec:
    accessModes: 
      - ReadWriteOnce
    capacity:
      storage: 1Gi
    nfs:
      path: /ose-nfs/volumeny/pv000
      server: 10.11.20.20
    persistentVolumeReclaimPolicy: Retain
    claimRef:
      name: gogs-postgres-data
      namespace: baza
- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: gogs-data-pv
  spec:
    accessModes: 
      - ReadWriteOnce
    capacity:
      storage: 1Gi
    nfs:
      path: /ose-nfs/volumeny/pv001
      server: 10.11.20.20
    persistentVolumeReclaimPolicy: Retain
    claimRef:
      name: gogs-data
      namespace: baza